export enum NavigationRoot {
  Profile = 'PROFILE',
  EditProfile = 'EDIT_PROFILE',
  GameInfo = 'GAME_INFO',
  Participants = 'PARTICIPANTS',
  Location = 'LOCATION',
  UserInfo = 'USER_INFO',
  ChooseGameType = 'CHOOSE_GAME_TYPE',
  FindGame = 'FIND_GAME',
  OwnLocation = 'FIND_OWN_LOCATION',
  EditGame = 'EDIT_GAME',
  EditLocation = 'EDIT_LOCATION',
  SportFilters = 'SPORT_FILTERS',
  Main = 'MAIN',
  Auth = 'AUTH',
  NotAuthorized = 'NOT_AUTHORIZED',
}
